spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ucDemo?useUnicode=true&characterEncoding=utf8
  freemarker:
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
#    template-loader-path: classpath:/templates/order #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'
server:
  port: 8081
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml